# Generated by Django 6.1.1 on 2026-09-09 19:39

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # docs/BACKEND_SCHEMA.md §4 — Django won't enable this on its own.
        CreateExtension("vector"),
        migrations.CreateModel(
            name='KnownSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offering_type', models.CharField(choices=[('homestay', 'Homestay'), ('guide', 'Guide'), ('artisan_experience', 'Artisan Experience'), ('other', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_unit', models.CharField(choices=[('night', 'Night'), ('person', 'Person'), ('experience', 'Experience')], max_length=16)),
                ('region', models.CharField(max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('needs_review', 'Needs Review'), ('live', 'Live'), ('inactive', 'Inactive')], default='pending_verification', max_length=32)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'region'], name='listings_li_status_072df9_idx')],
            },
        ),
    ]
